{{ if .Values.tests }}
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-smoke-test
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: minio-client
        image: quay.io/minio/minio:RELEASE.2024-03-15T01-07-19Z
        command:
        - /bin/sh
        - -c
        - |
          set -e # make sure the job fails if any instruction fails

          source /tmp/config.env;
          set -x;  # enable printing the command before execution (in the sub-shell)
          mc alias set minio https://minio.{{ .Release.Namespace }}.svc.cluster.local $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
          mc mb -p minio/test-encrypted-bucket;
          mc encrypt set sse-kms encryption-key minio/test-encrypted-bucket;
          mc ls minio;
          echo "This is a line of text" > /tmp/test-object;
          mc mv /tmp/test-object minio/test-encrypted-bucket;
          mc ls minio/test-encrypted-bucket;
          mc cat minio/test-encrypted-bucket/test-object
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /tmp/config.env
          subPath: config.env
          name: configuration
          readOnly: true
        - mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
          name: ca-bundle
          readOnly: true
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: ca-bundle
        configMap:
          defaultMode: 0444
          name: ca-bundle
      - name: configuration
        secret:
          defaultMode: 0440
          secretName: {{ .Values.tenant.secrets.existingSecret.name | default .Values.tenant.secrets.name}}
  backoffLimit: 5
{{ end }}
