{{ if or .Values.mutation.nodeSelector.enable .Values.validation.nodeSelector.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: set-node-labels
  namespace: gatekeeper-system
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: set-node-labels
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: set-node-labels
  namespace: gatekeeper-system
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
subjects:
- kind: ServiceAccount
  name: set-node-labels
  namespace: gatekeeper-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: set-node-labels
---
apiVersion: batch/v1
kind: Job
metadata:
  name: set-node-labels
  namespace: gatekeeper-system
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.30
        command:
        - /bin/bash
        - -c
        - |
          set -e # make sure the job fails if any instruction fails

          # Get worker nodes
          nodes=$(kubectl get nodes -l '!node-role.kubernetes.io/control-plane' -o name)

          # Set node labels (half hardened and half unhardened)
          nof_nodes=$(echo ${nodes} | wc -w)
          count=0
          for node in ${nodes}
          do
            if [ ${count} -lt $((${nof_nodes} / 2)) ]
            then
              value=hardened
            else
              value=unhardened
            fi

            kubectl label ${node} security-ring=${value} --overwrite

            count=$((count + 1))
          done
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      restartPolicy: Never
      serviceAccountName: set-node-labels
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{ end }}
