{{ if .Values.validation.nodeSelector.enable }}
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequirenodeselectorsequalto
  annotations:
    metadata.gatekeeper.sh/title: "Required Node Selector Equal To"
    metadata.gatekeeper.sh/version: 1.0.1
    description: >-
      Requires pods to contain nodeSelector key-value pairs. The expected value
      is retrieved by traversing the input review object.
spec:
  crd:
    spec:
      names:
        kind: K8sRequireNodeSelectorsEqualTo
      validation:
        openAPIV3Schema:
          type: object
          properties:
            nodeSelectors:
              description: List of required nodeSelectors.
              type: array
              items:
                description: The required nodeSelector.
                type: object
                properties:
                  key:
                    description: The required nodeSelector key.
                    type: string
                  value:
                    description: >-
                      The list of keys to navigate the input review object to
                      the expected nodeSelector value.
                    type: array
                    items:
                      type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequirenodeselectorsequalto

        import future.keywords.contains
        import future.keywords.if
        import future.keywords.in

        # missing node selector
        violation contains {"msg": msg} if {
          required := {nodeSelector.key | some nodeSelector in input.parameters.nodeSelectors}
          provided := {key | some key, _ in input.review.object.spec.nodeSelector}
          missing := required - provided
          count(missing) > 0

          podName := input.review.object.metadata.name
          msg := sprintf("pod <%v> does not specify the required nodeSelector keys <%v>", [podName, missing])
        }

        # wrong node selector value
        violation contains {"msg": msg} if {
          some nodeSelector in input.parameters.nodeSelectors
          required_value := object.get(input.review.object, nodeSelector.value, null)
          provided_value := input.review.object.spec.nodeSelector[nodeSelector.key]
          provided_value != required_value

          podName := input.review.object.metadata.name
          path_to_expected_value := sprintf(".%v", [concat(".", nodeSelector.value)]) # avoid leaking actual value
          msg := sprintf("pod <%v> has node selector <%v> set to a value different from the value of <%v>", [podName, nodeSelector.key, path_to_expected_value])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireNodeSelectorsEqualTo
metadata:
  name: uc1-workload-must-have-security-aware-scheduling
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: {{- toYaml .Values.validation.nodeSelector.match.namespaces | nindent 6 }}
    labelSelector:
      matchExpressions:
      - key: security-ring
        operator: Exists
  parameters:
    nodeSelectors:
    - key: security-ring
      value:
      - metadata
      - labels
      - security-ring
{{ end }}
