apiVersion: v2
name: certificate-management
description: A Helm chart for deploying a private certificate authority
version: 1.0.0
dependencies:
- name: cert-manager
  version: v1.17.1
  repository: https://charts.jetstack.io
- name: trust-manager
  version: v0.9.2
  repository: https://charts.jetstack.io
