apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-container-resource-cpu-requests
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  {{ toYaml .Values.mutation.resources.match | nindent 2 }}
  location: spec.containers[name:*].resources.requests.cpu
  parameters:
    pathTests:
    - subPath: spec.containers[name:*].resources.requests.cpu
      condition: MustNotExist
    assign:
      value: {{ .Values.mutation.resources.requests.cpu }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-container-resource-memory-requests
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  {{ toYaml .Values.mutation.resources.match | nindent 2 }}
  location: spec.containers[name:*].resources.requests.memory
  parameters:
    pathTests:
    - subPath: spec.containers[name:*].resources.requests.memory
      condition: MustNotExist
    assign:
      value: {{ .Values.mutation.resources.requests.memory }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-container-resource-cpu-limits
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  {{ toYaml .Values.mutation.resources.match | nindent 2 }}
  location: spec.containers[name:*].resources.limits.cpu
  parameters:
    pathTests:
    - subPath: spec.containers[name:*].resources.limits.cpu
      condition: MustNotExist
    assign:
      value: {{ .Values.mutation.resources.limits.cpu }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-container-resource-memory-limits
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  {{ toYaml .Values.mutation.resources.match | nindent 2 }}
  location: spec.containers[name:*].resources.limits.memory
  parameters:
    pathTests:
    - subPath: spec.containers[name:*].resources.limits.memory
      condition: MustNotExist
    assign:
      value: {{ .Values.mutation.resources.limits.memory}}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-initcontainer-resource-cpu-requests
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  {{ toYaml .Values.mutation.resources.match | nindent 2 }}
  location: spec.initContainers[name:*].resources.requests.cpu
  parameters:
    pathTests:
    - subPath: spec.initContainers[name:*].resources.requests.cpu
      condition: MustNotExist
    assign:
      value: {{ .Values.mutation.resources.requests.cpu }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-initcontainer-resource-memory-requests
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  {{ toYaml .Values.mutation.resources.match | nindent 2 }}
  location: spec.initContainers[name:*].resources.requests.memory
  parameters:
    pathTests:
    - subPath: spec.initContainers[name:*].resources.requests.memory
      condition: MustNotExist
    assign:
      value: {{ .Values.mutation.resources.requests.memory }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-initcontainer-resource-cpu-limits
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  {{ toYaml .Values.mutation.resources.match | nindent 2 }}
  location: spec.initContainers[name:*].resources.limits.cpu
  parameters:
    pathTests:
    - subPath: spec.initContainers[name:*].resources.limits.cpu
      condition: MustNotExist
    assign:
      value: {{ .Values.mutation.resources.limits.cpu }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-initcontainer-resource-memory-limits
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  {{ toYaml .Values.mutation.resources.match | nindent 2 }}
  location: spec.initContainers[name:*].resources.limits.memory
  parameters:
    pathTests:
    - subPath: spec.initContainers[name:*].resources.limits.memory
      condition: MustNotExist
    assign:
      value: {{ .Values.mutation.resources.limits.memory }}
