apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: gatekeeper
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    targetRevision: {{ .Values.gatekeeper.version }}
    helm:
      valuesObject:
        audit:
          resources:
            {{- toYaml .Values.gatekeeper.audit.resources | nindent 12 }}
        controllerManager:
          resources:
            {{- toYaml .Values.gatekeeper.controllerManager.resources | nindent 12 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
