name: build-helm-chart

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ github.token }}
          environment: github-pages
          onlyRemoveDeployments: true

  build_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: cleanup
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Publish Dev Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ github.token }}
        charts_dir: "./charts"
        target_dir: "./dev"
